### PR TITLE
Move sync folder into /var/www/public_html

### PR DESCRIPTION
**Pull request by loostro**
In order to not mix standard apache /var/www contents with the project, the project is moved to `/var/www/public_html` dir.

### CODE REVIEW

**Comment by loostro** [comment]
When provisioning VM, there will be some files created in `/var/www` by Apache install. These will clutter the project's directory. So I moved the synced folder to `/var/www/public_html` to avoid that.

**Comment by loostro** [comment]
@sescandell please review, have I missed anything?

**Comment by loostro** [comment]
OK, I've encountered a few problems with previous config.

Seems like `sync_type: default` is not fast enough, when doing `rm -rf prod_old/`. Then removeing many files in a nested tree structure (like symfony's cache dir is), the command returns before it actually deletes the files in current directory... which causes an error, when the command recursively tries to remove the parent directory - cannot remove directory that is not empty.

So I changed to the recommended `sync_type: nfs`.

This however, created other issues. For example in my project the [LoadRootData.php](https://github.com/helios-ag/FMElfinderBundle/blob/master/DataFixtures/ORM/LoadRootElement.php) from `helios-ag/FMElfinderBundle` throwed an error, bitching about permissions.

To fix that I've edited the `Vagrantfile` to use `vagrant` as owner and `www-data` as group and it seems everything is fine now.

**Comment by loostro** [comment]
*(...)  and it seems everything is fine now.* **WRONG!**

Reverting, looking for another solution :P

**Comment by sescandell** [comment]
Hi @loostro 

Changing to nfs might create some incompatibilities with Windows users. There is some ways to test the host and define dyamically the protocol to use.

Users rights access is also something we could configure. I have this ready in personnal projects.

As soon as I have time, I'll review all of this,

**Comment by loostro** [comment]
@sescandell I have a problem I was unable to solve. I am getting errors with file permissions. Also, the PuPHPet site has been updated and generates a diffrent config than the one you used when creating the demo. Since there is no documentation explaining the list of possible options (or I could not find one) I found it difficult to troubleshoot (well.. I did trial and error.. but that got me nowhere :/)

What we need is a config that:
a) vagrant user can read/write `/var/www/public_html`
b) www-data user can read/write `/var/www/public_html`
c) the cache is cleared without problems -> `rm app/cache/* -rf`must not fail
d) (preferably) the driver stays "default" (if possible) as it causes less problems

**Comment by loostro** [comment]
OK, it seems that the `copyCache` script was causing the trouble. I've created a clean new PuPHPet config, with only assets-install, cache-clear and 001-init-project scripts and it runs flawlessly on `sync_type: default`.

I'll copy the solution to the PR tomorrow.

**Comment by loostro** [comment]
OK I've found [this change](https://github.com/symfony2admingenerator/symfony2-admingenerator-demo-edition/commit/3242b661050255ce5dacf196fea5cfdd274ea317#diff-39be3a54c12f1ce91f871a1be7179eb1R24) may be relevant.. it sucks that every config change I have to destroy/provision again the box... it takes so much time to check :/

**Comment by loostro** [comment]
Finally. After a lot of digging I found out why you had to move cache&logs out of the synced directory. I've updated the scripts, adding a seperated `init-temp.sh`, which I will update in future to also move `uploads` directory outside of synced dir.

**Comment by loostro** [comment]
> For future reference [symfony2-on-vagrant](http://by-examples.net/2014/12/09/symfony2-on-vagrant.html)

**Comment by loostro** [comment]
One last problem is `500 Internal server error` on debug toolbar. Still don't know why I'm getting it.

**Comment by loostro** [comment]
Moved chown & chmod on temp dirs to seperate script `fix-permissions.sh`, which is called before and after each cache clear (just to be sure the whole temp dir is both vagrant and www-data writeable, to prevent errors).

**Comment by loostro** [comment]
Moved `sessions_dir` to `/tmp/generator/sessions` so we don't get logged out every time we clear cache :) Also changed the language to `en`. I hope you don't mind @sescandell. Updated `init-temp` script to make sure `/tmp/generator/sessions` exists.

**Comment by sescandell** [comment]
Hi @loostro 

I should deep in your changes this week-end.

I'm surprised you had so many troubles with this.

Thanks for your work

**Comment by sescandell** [comment]
Hi @loostro 

Could you tell me what the situation there?

Do you need anything from me?

**Comment by loostro** [comment]
@sescandell I plan to update the puphpet/vagrant to latest (while keeping the customizations) and re-test this branch before merging it, however I now understand where your customizations (cache in /tmp) came from and I learned how vagrant works on the way.

I think the last thing I'll do is moveing `upload` dir to `/tmp` and add some demonstration how to use LiipImagineBundle or VichUploaderBundle combined with Admingenerator.

(eg. when you create "uploaded" files in DataFixtures -> to prevent the same errors that logs/cache dirs had -> upload dir has to be on native filesystem when in vagrant enviroment).

**Comment by loostro** [comment]
Thanks, but I think I'm OK now. I've got now an understanding how vagrant/puphpet works, so I'll be OK :)

**Comment by sescandell** [comment]
:+1: 

If you move upload dir to /tmp, it means that it will not be persistent. For upload dirs, I'm not sure this is really relevant as files are not processed and accessed so often.

Ok for Liip and Vich, let me know if you want some examples, I have somes.

**Comment by sescandell** [comment]
Hi @loostro 

I was wondering something: what about moving to Docker instead?
I didn't had time to dive into Docker yet (but planned to), but it seems to be lighter than Vagrant/Puppet + maybe removing issues with IO latency.

Maybe in a second step?

I really don't know, just an idea like that...

**Comment by loostro** [comment]
Let's make another branch with docker and compare both, then choose best.

**Comment by sescandell** [comment]
Sounds like a good idea :+1:

**Pull request merged**
